### ISSUE TITLE
2x errors in the book

### ISSUE THREAD

**Issue by gunnars04** [PacktPublishing/Developing-Solutions-for-Microsoft-Azure-AZ-204-Exam-Guide-2nd-Edition#13]
1. In this file:
Chapter02\02-appsettings-logging\Pages\Shared\_Layout.cshtml
When I run the project, chrome can't find the css (see chrome console window), so I had to change it to this:
`  <link rel="stylesheet" href="~/appsettings-logging.styles.css" asp-append-version="true" />`
![image](https://github.com/PacktPublishing/Developing-Solutions-for-Microsoft-Azure-AZ-204-Exam-Guide-2nd-Edition/assets/10080542/d487111f-eba8-4675-bfc2-63366289f9d2)

2. There is a typo here (chapter 3, excercise 5), the root path wont give you the weather data:
![image](https://github.com/PacktPublishing/Developing-Solutions-for-Microsoft-Azure-AZ-204-Exam-Guide-2nd-Edition/assets/10080542/2f26dbbe-43be-4292-ba9d-55f72aa3cbdf)
![image](https://github.com/PacktPublishing/Developing-Solutions-for-Microsoft-Azure-AZ-204-Exam-Guide-2nd-Edition/assets/10080542/812ddf4d-b4dc-459b-ac62-9df285607962)
You have to use this endpoint (I found out when I ran this in Visual Studio 2022):
https://localhost:7182/WeatherForecast
![image](https://github.com/PacktPublishing/Developing-Solutions-for-Microsoft-Azure-AZ-204-Exam-Guide-2nd-Edition/assets/10080542/46e49767-4495-437b-885b-ce613b3e499f)

I b.t.w. love this book, very well done and I love all the explenations and detailed excercises. I've been struggling learning this for a year so this book is truely a godsend! :-)

**Comment by paul-msft** [comment]
Thanks for the feedback, @gunnars04! That line of code has been removed now, as it's referencing a file that doesn't exist. The exercise you refer to with the typo is accurate because the steps are to run the API first (which is where the `weatherforecast` endpoint is), then run the app and navigate to the app in the browser. It's the web app that uses the `weatherforecast`, so you don't have to in the browser :) 
![image](https://github.com/user-attachments/assets/7c265bce-9d90-4dd4-9e63-93a2d47d337a)
